module.exports = {
  ignorePatterns: [
    "projects/**/*",
    "e2e/**",
    "src/app/api/**",
    "src/app/async-api/**",
    "src/assets/scripts/**",
    "node_modules",
    "dist",
    "mock-server",
    "jest.config.js",
    "fixtures",
    "coverage",
    "__snapshots__",
    "karma.conf.js",
    "**/*.spec.ts",
  ],
  plugins: [
    "@typescript-eslint",
    "prefer-arrow",
    "import",
    "jsdoc",
    "unicorn",
    "sort-imports-es6-autofix",
  ],
  env: {
    browser: true,
    node: true,
    es6: true,
  },
  overrides: [
    {
      files: ["*.ts", "*.js"],
      rules: {
        "import/no-unresolved": "off",
        "array-callback-return": [
          "error",
          {
            allowImplicit: true,
            checkForEach: true,
          },
        ],
        "constructor-super": "error",
        "getter-return": "error",
        "no-async-promise-executor": "error",
        "no-class-assign": "error",
        "no-compare-neg-zero": "error",
        "no-cond-assign": "error",
        "no-const-assign": "error",
        "no-constructor-return": "error",
        "no-control-regex": "error",
        "no-debugger": "error",
        "no-dupe-args": "error",
        "no-dupe-class-members": "error",
        "no-dupe-else-if": "error",
        "no-dupe-keys": "error",
        "no-duplicate-case": "error",
        "no-duplicate-imports": "error",
        "no-empty-character-class": "error",
        "no-empty-pattern": "error",
        "no-ex-assign": "error",
        "no-fallthrough": "error",
        "no-func-assign": "error",
        "no-import-assign": "error",
        "no-invalid-regexp": "error",
        "no-irregular-whitespace": "error",
        "no-loss-of-precision": "error",
        "no-misleading-character-class": "error",
        "no-new-symbol": "error",
        "no-obj-calls": "error",
        "no-promise-executor-return": "error",
        "no-prototype-builtins": "error",
        "no-self-assign": "error",
        "no-self-compare": "error",
        "no-setter-return": "error",
        "no-sparse-arrays": "error",
        "no-template-curly-in-string": "error",
        "no-this-before-super": "error",
        "no-undef": "error",
        "no-unexpected-multiline": "error",
        "no-unmodified-loop-condition": "error",
        "no-unreachable": "error",
        "no-unreachable-loop": "error",
        "no-unsafe-finally": "error",
        "no-unsafe-negation": "error",
        "no-unsafe-optional-chaining": "error",
        "no-unused-vars": "error",
        "no-use-before-define": "error",
        "no-useless-backreference": "error",
        "require-atomic-updates": "error",
        "use-isnan": "error",
        "valid-typeof": "error",
        "block-scoped-var": "error",
        "consistent-return": "error",
        curly: ["error", "all"],
        "default-case-last": "error",
        "default-param-last": "error",
        eqeqeq: "error",
        "func-name-matching": "error",
        "func-names": ["error", "as-needed"],
        "func-style": [
          "error",
          "declaration",
          {
            allowArrowFunctions: true,
          },
        ],
        "grouped-accessor-pairs": ["error", "getBeforeSet"],
        "guard-for-in": "error",
        "id-denylist": [
          "error",
          "callback",
          "e",
          "a",
          "b",
          "c",
          "sex",
          "form",
          "lst",
          "elem",
          "str",
          "num",
        ],
        "max-classes-per-file": ["error", 1],
        "max-depth": ["error", 3],
        "max-len": [
          "error",
          {
            code: 120,
            ignorePattern: "^import\\s.+\\sfrom\\s.+;$",
            ignoreUrls: true,
          },
        ],
        "max-lines": [
          "error",
          {
            max: 300,
            skipComments: true,
          },
        ],
        "max-lines-per-function": [
          "error",
          {
            max: 35,
            skipBlankLines: true,
            skipComments: true,
          },
        ],
        "max-nested-callbacks": ["error", 3],
        "max-params": ["error", 8],
        "max-statements": ["error", 15],
        "new-cap": [
          "error",
          {
            capIsNew: false,
            capIsNewExceptions: [
              "Pipe",
              "NgModule",
              "NgComponent",
              "Injectable",
              "Inject",
              "Directive",
              "NgDirective",
              "Component",
              "Optional",
              "HostBinding",
              "Input",
              "Output",
              "HostListener",
              "ViewChild",
              "ViewChildren",
            ],
          },
        ],
        "no-alert": "error",
        "no-array-constructor": "error",
        "no-await-in-loop": "error",
        "no-bitwise": "error",
        "no-caller": "error",
        "no-case-declarations": "error",
        "no-confusing-arrow": [
          "off",
          {
            allowParens: true,
          },
        ],
        "no-console": "error",
        "no-delete-var": "error",
        "no-div-regex": "error",
        "no-empty": [
          "error",
          {
            allowEmptyCatch: true,
          },
        ],
        "no-eq-null": "error",
        "no-eval": "error",
        "no-extend-native": "error",
        "no-extra-bind": "error",
        "no-extra-label": "error",
        "no-extra-semi": "error",
        "no-floating-decimal": "error",
        "no-global-assign": "error",
        "no-implicit-coercion": "error",
        "no-implied-eval": "error",
        "no-inner-declarations": ["error", "both"],
        "no-iterator": "error",
        "no-label-var": "error",
        "no-labels": "error",
        "no-lone-blocks": "error",
        "no-lonely-if": "error",
        "no-loop-func": "error",
        "no-magic-numbers": [
          "error",
          {
            ignore: [0, 1, -1],
          },
        ],
        "no-mixed-operators": "error",
        "no-mixed-spaces-and-tabs": "error",
        "no-multi-assign": "error",
        "no-multi-spaces": "error",
        "no-multi-str": "error",
        "no-negated-condition": "error",
        "no-nested-ternary": "error",
        "no-new-func": "error",
        "no-new-object": "error",
        "no-new-wrappers": "error",
        "no-nonoctal-decimal-escape": "error",
        "no-octal": "error",
        "no-octal-escape": "error",
        "no-proto": "error",
        "no-redeclare": "error",
        "no-regex-spaces": "error",
        "no-return-assign": "error",
        "no-return-await": "error",
        "no-script-url": "error",
        "no-sequences": "error",
        "no-shadow": "error",
        "no-shadow-restricted-names": "error",
        "no-tabs": "error",
        "no-throw-literal": "error",
        "no-trailing-spaces": "error",
        "no-unneeded-ternary": "error",
        "no-unused-expressions": "error",
        "no-unused-labels": "error",
        "no-useless-call": "error",
        "no-useless-catch": "error",
        "no-useless-computed-key": "error",
        "no-useless-concat": "error",
        "no-useless-escape": "error",
        "no-useless-rename": "error",
        "no-useless-return": "error",
        "no-var": "error",
        "no-void": [
          "error",
          {
            allowAsStatement: true,
          },
        ],
        "no-with": "error",
        "object-shorthand": ["error", "always"],
        "one-var": ["error", "never"],
        "operator-assignment": ["error", "always"],
        "prefer-arrow-callback": "error",
        "prefer-arrow/prefer-arrow-functions": [
          "error",
          {
            singleReturnOnly: true,
            allowStandaloneDeclarations: true,
          },
        ],
        "prefer-const": "error",
        "prefer-exponentiation-operator": "error",
        "prefer-named-capture-group": "error",
        "prefer-numeric-literals": "error",
        "prefer-object-spread": "error",
        "prefer-promise-reject-errors": "error",
        "prefer-regex-literals": "error",
        "prefer-rest-params": "error",
        "prefer-spread": "error",
        "prefer-template": "error",
        "quote-props": [
          "error",
          "consistent-as-needed",
          {
            numbers: true,
            keywords: true,
          },
        ],
        "require-await": "error",
        "require-yield": "error",
        "sort-keys": [
          "off",
          "asc",
          {
            caseSensitive: false,
            minKeys: 6,
          },
        ],
        "spaced-comment": ["error", "always"],
        "symbol-description": "error",
        yoda: ["error", "never"],
        "array-bracket-newline": ["error", "consistent"],
        "array-bracket-spacing": ["error", "never"],
        "array-element-newline": ["error", "consistent"],
        "arrow-parens": ["error", "as-needed"],
        "arrow-spacing": [
          "error",
          {
            before: true,
            after: true,
          },
        ],
        "block-spacing": ["error", "always"],
        "brace-style": [
          "error",
          "1tbs",
          {
            allowSingleLine: true,
          },
        ],
        "comma-dangle": ["error", "always-multiline"],
        "computed-property-spacing": ["error", "never"],
        "dot-location": ["error", "property"],
        "eol-last": ["error", "always"],
        "func-call-spacing": ["error", "never"],
        "function-call-argument-newline": ["error", "consistent"],
        "function-paren-newline": ["error", "consistent"],
        "generator-star-spacing": [
          "error",
          {
            before: true,
            after: false,
          },
        ],
        "implicit-arrow-linebreak": ["error", "beside"],
        indent: ["error", 4],
        "keyword-spacing": [
          "error",
          {
            before: true,
            after: true,
          },
        ],
        "linebreak-style": ["off", "unix"],
        "lines-between-class-members": [
          "error",
          "always",
          {
            exceptAfterSingleLine: false,
          },
        ],
        "max-statements-per-line": [
          "error",
          {
            max: 1,
          },
        ],
        "multiline-ternary": ["error", "always-multiline"],
        "new-parens": ["error", "always"],
        "newline-per-chained-call": [
          "error",
          {
            ignoreChainWithDepth: 2,
          },
        ],
        "no-extra-parens": ["error", "all"],
        "no-multiple-empty-lines": [
          "error",
          {
            max: 3,
            maxEOF: 1,
            maxBOF: 0,
          },
        ],
        "no-whitespace-before-property": "error",
        "object-curly-spacing": ["error", "always"],
        "object-property-newline": [
          "error",
          {
            allowAllPropertiesOnSameLine: true,
          },
        ],
        "operator-linebreak": ["error", "before"],
        "padded-blocks": [
          "error",
          {
            classes: "always",
          },
        ],
        quotes: ["error", "single"],
        "rest-spread-spacing": ["error", "never"],
        semi: ["error", "always"],
        "semi-spacing": [
          "error",
          {
            before: false,
            after: true,
          },
        ],
        "semi-style": ["error", "last"],
        "space-before-blocks": ["error", "always"],
        "space-before-function-paren": [
          "error",
          {
            anonymous: "never",
            named: "never",
            asyncArrow: "always",
          },
        ],
        "space-in-parens": ["error", "never"],
        "space-infix-ops": [
          "error",
          {
            int32Hint: false,
          },
        ],
        "space-unary-ops": [
          "error",
          {
            words: true,
            nonwords: false,
          },
        ],
        "switch-colon-spacing": [
          "error",
          {
            after: true,
            before: false,
          },
        ],
        "template-curly-spacing": ["error", "never"],
        "template-tag-spacing": ["error", "never"],
        "unicode-bom": ["error", "never"],
        "wrap-iife": ["error", "any"],
        "yield-star-spacing": ["error", "before"],
        complexity: ["error", 6],
        "dot-notation": "error",
        "id-length": [
          "error",
          {
            min: 2,
            max: 40,
            exceptions: [
              "x",
              "y",
              "i",
              "j",
              "k",
              "min",
              "max",
              "lat",
              "lng",
              "fb",
              "el",
              "cd",
              "db",
              "_",
              "L",
            ],
          },
        ],
        "no-param-reassign": [
          "error",
          {
            props: true,
          },
        ],
        "no-constant-condition": "error",
        "no-restricted-syntax": ["error"],
      },
    },
    {
      files: ["*.ts", "*.tsx"],
      parser: "@typescript-eslint/parser",
      parserOptions: {
        ecmaVersion: 2020,
        sourceType: "module",
        project: ["tsconfig.json"],
        createDefaultProgram: true,
      },
      rules: {
        "sort-imports-es6-autofix/sort-imports-es6": [
          "error",
          {
            memberSyntaxSortOrder: ["none", "single", "all", "multiple"],
            ignoreCase: true,
          },
        ],
        "constructor-super": "off",
        "getter-return": "off",
        "no-const-assign": "off",
        "no-dupe-args": "off",
        "no-dupe-keys": "off",
        "no-func-assign": "off",
        "no-import-assign": "off",
        "no-new-symbol": "off",
        "no-obj-calls": "off",
        "no-setter-return": "off",
        "no-this-before-super": "off",
        "no-undef": "off",
        "no-unreachable": "off",
        "no-unsafe-negation": "off",
        "valid-typeof": "off",
        "@typescript-eslint/adjacent-overload-signatures": "error",
        "@typescript-eslint/array-type": [
          "error",
          {
            default: "array-simple",
          },
        ],
        "@typescript-eslint/await-thenable": "error",
        "@typescript-eslint/ban-ts-comment": [
          "error",
          {
            "ts-expect-error": "allow-with-description",
            minimumDescriptionLength: 10,
          },
        ],
        "@typescript-eslint/ban-types": "error",
        "brace-style": "off",
        "@typescript-eslint/brace-style": [
          "error",
          "1tbs",
          {
            allowSingleLine: true,
          },
        ],
        "comma-dangle": "off",
        "@typescript-eslint/comma-dangle": ["error", "always-multiline"],
        "@typescript-eslint/consistent-type-definitions": [
          "error",
          "interface",
        ],
        "default-param-last": "off",
        "@typescript-eslint/default-param-last": "error",
        "dot-notation": "off",
        "@typescript-eslint/dot-notation": "error",
        "@typescript-eslint/explicit-member-accessibility": [
          "error",
          {
            accessibility: "explicit",
            overrides: {
              constructors: "off",
            },
          },
        ],
        "func-call-spacing": "off",
        "@typescript-eslint/func-call-spacing": ["error", "never"],
        indent: "off",
        "@typescript-eslint/indent": [
          "error",
          4,
          {
            SwitchCase: 1,
            flatTernaryExpressions: false,
            ignoredNodes: [
              "TSUnionType",
              "TSIntersectionType",
              "ClassDeclaration",
              "PropertyDefinition",
              "Decorator",
              "TSParameterProperty",
            ],
          },
        ],
        "keyword-spacing": "off",
        "@typescript-eslint/keyword-spacing": [
          "error",
          {
            before: true,
            after: true,
          },
        ],
        "lines-between-class-members": "off",
        "@typescript-eslint/lines-between-class-members": [
          "error",
          "always",
          {
            exceptAfterSingleLine: false,
          },
        ],
        "@typescript-eslint/member-delimiter-style": "error",
        "@typescript-eslint/method-signature-style": ["error", "method"],
        "@typescript-eslint/naming-convention": [
          "error",
          {
            selector: "default",
            format: ["camelCase"],
            leadingUnderscore: "allow",
            trailingUnderscore: "allow",
          },
          {
            selector: ["objectLiteralProperty", "typeProperty", "accessor"],
            format: ["camelCase", "snake_case"],
            leadingUnderscore: "allow",
            trailingUnderscore: "allow",
          },
          {
            selector: ["variable", "classProperty"],
            format: ["camelCase", "UPPER_CASE"],
            leadingUnderscore: "allow",
            trailingUnderscore: "allow",
          },
          {
            selector: "typeLike",
            format: ["PascalCase"],
          },
          {
            selector: ["objectLiteralProperty", "typeProperty"],
            format: null,
            filter: {
              regex: "^(Authorization)$|^([0-9]+)$",
              match: true,
            },
          },
          {
            selector: "variable",
            format: null,
            filter: {
              regex: "^([a-zA-Z]+Injector)$",
              match: true,
            },
          },
          {
            selector: "classProperty",
            format: null,
            filter: {
              regex: "^(LayerClass)$",
              match: true,
            },
          },
          {
            selector: [
              "classProperty",
              "objectLiteralProperty",
              "typeProperty",
              "classMethod",
              "objectLiteralMethod",
              "typeMethod",
              "accessor",
              "enumMember",
            ],
            format: null,
            modifiers: ["requiresQuotes"],
          },
        ],
        "no-array-constructor": "off",
        "@typescript-eslint/no-array-constructor": "error",
        "@typescript-eslint/no-confusing-void-expression": "error",
        "no-dupe-class-members": "off",
        "@typescript-eslint/no-dupe-class-members": "error",
        "no-duplicate-imports": "off",
        "@typescript-eslint/no-duplicate-imports": "error",
        "@typescript-eslint/no-dynamic-delete": "error",
        "@typescript-eslint/no-empty-interface": "error",
        "@typescript-eslint/no-explicit-any": "error",
        "@typescript-eslint/no-extra-non-null-assertion": "error",
        "no-extra-parens": "off",
        "@typescript-eslint/no-extra-parens": [
          "error",
          "all",
          {
            nestedBinaryExpressions: false,
          },
        ],
        "no-extra-semi": "off",
        "@typescript-eslint/no-extra-semi": "error",
        "@typescript-eslint/no-extraneous-class": [
          "error",
          {
            allowConstructorOnly: true,
            allowWithDecorator: true,
          },
        ],
        "@typescript-eslint/no-floating-promises": "error",
        "@typescript-eslint/no-for-in-array": "error",
        "@typescript-eslint/no-implicit-any-catch": "error",
        "no-implied-eval": "off",
        "@typescript-eslint/no-implied-eval": "error",
        "@typescript-eslint/no-inferrable-types": "error",
        "@typescript-eslint/no-invalid-void-type": "error",
        "no-loop-func": "off",
        "@typescript-eslint/no-loop-func": "error",
        "no-loss-of-precision": "off",
        "@typescript-eslint/no-loss-of-precision": "error",
        "no-magic-numbers": "off",
        "@typescript-eslint/no-magic-numbers": [
          "error",
          {
            ignore: [0, 1, -1],
            ignoreReadonlyClassProperties: true,
          },
        ],
        "@typescript-eslint/no-misused-new": "error",
        "@typescript-eslint/no-misused-promises": [
          "error",
          {
            checksVoidReturn: false,
          },
        ],
        "@typescript-eslint/no-namespace": "error",
        "@typescript-eslint/no-non-null-asserted-optional-chain": "error",
        "@typescript-eslint/no-non-null-assertion": "error",
        "@typescript-eslint/no-parameter-properties": [
          "error",
          {
            allows: [
              "private readonly",
              "protected readonly",
              "public readonly",
            ],
          },
        ],
        "no-redeclare": "off",
        "@typescript-eslint/no-redeclare": "error",
        "@typescript-eslint/no-require-imports": "error",
        "no-shadow": "off",
        "@typescript-eslint/no-shadow": "error",
        "@typescript-eslint/no-this-alias": "error",
        "no-throw-literal": "off",
        "@typescript-eslint/no-throw-literal": "error",
        "@typescript-eslint/no-unnecessary-boolean-literal-compare": "error",
        "@typescript-eslint/no-unnecessary-qualifier": "error",
        "@typescript-eslint/no-unnecessary-type-arguments": "error",
        "@typescript-eslint/no-unnecessary-type-assertion": "error",
        "@typescript-eslint/no-unsafe-member-access": "error",
        "no-unused-expressions": "off",
        "@typescript-eslint/no-unused-expressions": "error",
        "no-unused-vars": "off",
        "@typescript-eslint/no-unused-vars": [
          "error",
          {
            vars: "local",
            args: "none",
            ignoreRestSiblings: true,
          },
        ],
        "no-use-before-define": "off",
        "@typescript-eslint/no-use-before-define": "error",
        "object-curly-spacing": "off",
        "@typescript-eslint/object-curly-spacing": ["error", "always"],
        "@typescript-eslint/prefer-for-of": "error",
        "@typescript-eslint/prefer-function-type": "error",
        "@typescript-eslint/prefer-namespace-keyword": "error",
        "@typescript-eslint/prefer-optional-chain": "error",
        "@typescript-eslint/prefer-readonly": "error",
        quotes: "off",
        "@typescript-eslint/quotes": ["error", "single"],
        "require-await": "off",
        "@typescript-eslint/require-await": "error",
        "@typescript-eslint/restrict-plus-operands": [
          "error",
          {
            checkCompoundAssignments: true,
          },
        ],
        "@typescript-eslint/restrict-template-expressions": "error",
        "no-return-await": "off",
        "@typescript-eslint/return-await": "error",
        semi: "off",
        "@typescript-eslint/semi": ["error", "always"],
        "space-before-function-paren": "off",
        "@typescript-eslint/space-before-function-paren": [
          "error",
          {
            anonymous: "never",
            named: "never",
            asyncArrow: "always",
          },
        ],
        "space-infix-ops": "off",
        "@typescript-eslint/space-infix-ops": [
          "error",
          {
            int32Hint: false,
          },
        ],
        "@typescript-eslint/triple-slash-reference": [
          "error",
          {
            types: "prefer-import",
          },
        ],
        "@typescript-eslint/type-annotation-spacing": [
          "error",
          {
            before: false,
            after: true,
            overrides: {
              arrow: {
                before: true,
                after: true,
              },
            },
          },
        ],
        "@typescript-eslint/unbound-method": [
          "error",
          {
            ignoreStatic: true,
          },
        ],
        "@typescript-eslint/unified-signatures": "error",
        "import/no-duplicates": "error",
        "jsdoc/require-jsdoc": "error",
        "jsdoc/no-types": "error",
        "unicorn/filename-case": [
          "error",
          {
            case: "kebabCase",
          },
        ],
        "@typescript-eslint/ban-tslint-comment": "error",
        "@typescript-eslint/class-literal-property-style": ["error", "fields"],
        "@typescript-eslint/consistent-indexed-object-style": [
          "error",
          "record",
        ],
        "@typescript-eslint/consistent-type-assertions": "error",
        "@typescript-eslint/no-base-to-string": "error",
        "@typescript-eslint/no-confusing-non-null-assertion": "error",
        "@typescript-eslint/no-non-null-asserted-nullish-coalescing": "error",
        "@typescript-eslint/no-unnecessary-condition": "warn",
        "@typescript-eslint/no-unnecessary-type-constraint": "error",
        "@typescript-eslint/no-unsafe-argument": "warn",
        "@typescript-eslint/no-unsafe-assignment": "warn",
        "@typescript-eslint/no-unsafe-call": "error",
        "@typescript-eslint/no-unsafe-return": "error",
        "@typescript-eslint/no-var-requires": "error",
        "@typescript-eslint/non-nullable-type-assertion-style": "error",
        "@typescript-eslint/prefer-as-const": "error",
        "@typescript-eslint/prefer-enum-initializers": "error",
        "@typescript-eslint/prefer-includes": "error",
        "@typescript-eslint/prefer-literal-enum-member": "error",
        "@typescript-eslint/prefer-nullish-coalescing": "error",
        "@typescript-eslint/prefer-reduce-type-parameter": "error",
        "@typescript-eslint/prefer-regexp-exec": "error",
        "@typescript-eslint/prefer-return-this-type": "error",
        "@typescript-eslint/prefer-string-starts-ends-with": "error",
        "@typescript-eslint/prefer-ts-expect-error": "error",
        "@typescript-eslint/require-array-sort-compare": [
          "error",
          {
            ignoreStringArrays: true,
          },
        ],
        "@typescript-eslint/sort-type-union-intersection-members": "error",
        "@typescript-eslint/switch-exhaustiveness-check": "error",
      },
    },
  ],
};
