module.exports = {
  extends: ["stylelint-config-rational-order-fix"],
  ignoreFiles: ["dist/", "node_modules/", "cache/", "*.md", "*.html"],
  customSyntax: "postcss-scss",
  plugins: ["stylelint-order", "stylelint-scss"],
  rules: {
    "order/order": [
      {
        type: "at-rule",
        name: "media",
      },
      {
        type: "rule",
        selector: "^.",
      },
      {
        type: "rule",
        selector: "^&::(before|after)",
      },
      {
        type: "rule",
        selector: "^&:\\w",
      },
      {
        type: "rule",
        selector: "^&_",
      },
    ],
    "at-rule-no-unknown": [
      true,
      {
        ignoreAtRules: [
          "include",
          "import",
          "use",
          "forward",
          "extend",
          "each",
          "mixin",
        ],
      },
    ],
    "block-no-empty": true,
    "color-no-invalid-hex": true,
    "comment-no-empty": true,
    "custom-property-no-missing-var-function": true,
    "declaration-block-no-duplicate-custom-properties": true,
    "declaration-block-no-duplicate-properties": true,
    "declaration-block-no-shorthand-property-overrides": true,
    "font-family-no-duplicate-names": true,
    "font-family-no-missing-generic-family-keyword": true,
    "function-calc-no-unspaced-operator": true,
    "function-linear-gradient-no-nonstandard-direction": true,
    "keyframe-declaration-no-important": true,
    "media-feature-name-no-unknown": true,
    "named-grid-areas-no-invalid": true,
    "no-duplicate-at-import-rules": true,
    "no-duplicate-selectors": true,
    "no-extra-semicolons": true,
    "no-invalid-double-slash-comments": true,
    "property-no-unknown": true,
    "selector-pseudo-class-no-unknown": [
      true,
      {
        ignorePseudoClasses: ["host", "host-context"],
      },
    ],
    "selector-pseudo-element-no-unknown": [
      true,
      {
        ignorePseudoElements: ["ng-deep"],
      },
    ],
    "string-no-newline": true,
    "unit-no-unknown": true,
    "alpha-value-notation": "number",
    "at-rule-no-vendor-prefix": true,
    "color-function-notation": "modern",
    "color-named": "never",
    "declaration-block-no-redundant-longhand-properties": true,
    "declaration-block-single-line-max-declarations": 1,
    "font-weight-notation": "numeric",
    "function-url-no-scheme-relative": true,
    "hue-degree-notation": "number",
    "keyframes-name-pattern": [
      "^([a-z]*)(-[a-z]+)*$",
      {
        message: "Expected keyframe name to be kebab-case",
      },
    ],
    "length-zero-no-unit": true,
    "max-nesting-depth": 5,
    "media-feature-name-no-vendor-prefix": true,
    "number-max-precision": 2,
    "property-no-vendor-prefix": true,
    "selector-attribute-name-disallowed-list": ["id", "class"],
    "selector-id-pattern": [
      "^([a-z]*)(-[a-z]+)*$",
      {
        message: "Expected id selector to be kebab-case",
      },
    ],
    "selector-max-class": 5,
    "selector-max-combinators": 5,
    "selector-max-compound-selectors": 5,
    "selector-max-empty-lines": 0,
    "selector-max-id": 3,
    "selector-max-pseudo-class": 5,
    "selector-max-type": 5,
    "selector-max-universal": 2,
    "selector-pseudo-element-colon-notation": "double",
    "shorthand-property-no-redundant-values": true,
    "time-min-milliseconds": 100,
    "unit-allowed-list": ["px", "em", "deg", "vh", "vw", "%", "s", "ms", "fr"],
    "value-no-vendor-prefix": true,
    "at-rule-empty-line-before": [
      "always",
      {
        except: [
          "after-same-name",
          "inside-block",
          "blockless-after-same-name-blockless",
          "blockless-after-blockless",
          "first-nested",
        ],
        ignore: ["after-comment"],
      },
    ],
    "at-rule-name-case": "lower",
    "at-rule-name-newline-after": "always-multi-line",
    "at-rule-name-space-after": "always-single-line",
    "at-rule-semicolon-newline-after": "always",
    "at-rule-semicolon-space-before": "never",
    "block-closing-brace-empty-line-before": "never",
    "block-closing-brace-newline-after": "always",
    "block-closing-brace-newline-before": "always",
    "block-opening-brace-newline-after": "always",
    "block-opening-brace-space-after": "always-single-line",
    "block-opening-brace-space-before": "always",
    "color-hex-case": "lower",
    "comment-whitespace-inside": "always",
    "custom-property-empty-line-before": [
      "always",
      {
        except: ["after-comment", "after-custom-property", "first-nested"],
      },
    ],
    "declaration-bang-space-after": "never",
    "declaration-bang-space-before": "always",
    "declaration-block-semicolon-newline-after": "always",
    "declaration-block-semicolon-newline-before": "never-multi-line",
    "declaration-block-semicolon-space-after": "always-single-line",
    "declaration-block-semicolon-space-before": "never",
    "declaration-block-trailing-semicolon": "always",
    "declaration-colon-space-after": "always",
    "declaration-colon-space-before": "never",
    "font-family-name-quotes": "always-unless-keyword",
    "function-comma-space-after": "always",
    "function-comma-space-before": "never",
    "function-name-case": "lower",
    "function-parentheses-space-inside": "never",
    "function-url-quotes": "always",
    "function-whitespace-after": "always",
    indentation: 4,
    "max-empty-lines": 3,
    "max-line-length": 160,
    "media-feature-colon-space-after": "always",
    "media-feature-colon-space-before": "never",
    "media-feature-name-case": "lower",
    "media-feature-parentheses-space-inside": "never",
    "media-feature-range-operator-space-after": "always",
    "media-feature-range-operator-space-before": "always",
    "media-query-list-comma-newline-after": "never-multi-line",
    "media-query-list-comma-newline-before": "never-multi-line",
    "media-query-list-comma-space-after": "always",
    "media-query-list-comma-space-before": "never",
    "no-empty-first-line": true,
    "no-eol-whitespace": true,
    "no-irregular-whitespace": true,
    "no-missing-end-of-source-newline": true,
    "number-leading-zero": "always",
    "number-no-trailing-zeros": true,
    "property-case": "lower",
    "selector-attribute-brackets-space-inside": "always",
    "selector-attribute-operator-space-after": "never",
    "selector-attribute-operator-space-before": "never",
    "selector-attribute-quotes": "always",
    "selector-combinator-space-after": "always",
    "selector-combinator-space-before": "always",
    "selector-list-comma-newline-after": "always",
    "selector-list-comma-newline-before": "never-multi-line",
    "selector-list-comma-space-after": "always-single-line",
    "selector-list-comma-space-before": "never",
    "selector-pseudo-class-case": "lower",
    "selector-pseudo-class-parentheses-space-inside": "never",
    "selector-pseudo-element-case": "lower",
    "selector-type-case": "lower",
    "string-quotes": "single",
    "unit-case": "lower",
    "value-keyword-case": "lower",
    "value-list-comma-newline-before": "never-multi-line",
    "value-list-comma-space-after": "always-single-line",
    "value-list-comma-space-before": "never",
    "scss/at-each-key-value-single-line": true,
    "scss/at-function-parentheses-space-before": "never",
    "scss/at-if-closing-brace-newline-after": "always-last-in-chain",
    "scss/at-if-no-null": true,
    "scss/at-import-partial-extension": "always",
    "scss/at-mixin-named-arguments": "always",
    "scss/at-mixin-parentheses-space-before": "never",
    "scss/at-rule-no-unknown": true,
    "scss/dollar-variable-colon-space-after": "always-single-line",
    "scss/dollar-variable-colon-space-before": "never",
    "scss/double-slash-comment-whitespace-inside": "always",
    "scss/comment-no-empty": true,
    "scss/declaration-nested-properties": "never",
    "scss/function-quote-no-quoted-strings-inside": true,
    "scss/function-unquote-no-unquoted-strings-inside": true,
    "scss/operator-no-newline-after": true,
    "scss/operator-no-newline-before": true,
    "scss/operator-no-unspaced": true,
    "scss/no-duplicate-dollar-variables": true,
    "scss/no-duplicate-mixins": true,
  },
};
